name: Build AppImage

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install FUSE (for AppImage)
        run: sudo apt-get update && sudo apt-get install -y libfuse2

      - name: Download appimagetool
        run: |
          curl -LO https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Prepare AppDir
        run: |
          # Create AppDir directory
          mkdir -p AppDir

          # Copy and sanitize the desktop file (must be named *.desktop)
          cp moonlight.desktop AppDir/
          sed -i '/^Icon=/d' AppDir/moonlight.desktop

          # Copy your wrapper and installer scripts
          cp wrapper.sh install.sh A
