name: Build AppImage

on:
  push:
    # trigger when you tag a new release, e.g. v1.2.3
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install FUSE and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 curl

      - name: Download appimagetool
        run: |
          curl -LO https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Prepare AppDir
        run: |
          # clean any previous build
          rm -rf AppDir
          mkdir -p AppDir

          # strip out Icon= (we don’t bundle an icon)
          sed '/^Icon=/d' moonlight.desktop > AppDir/moonlight.desktop

          # copy your scripts
          cp wrapper.sh install.sh AppDir/
          chmod +x AppDir/wrapper.sh AppDir/install.sh

          # AppRun stub: when user double-clicks the .AppImage, run install.sh
          cat > AppDir/AppRun << 'EOF'
#!/usr/bin/env bash
DIR="$(dirname "$(readlink -f "$0")")"
"$DIR/install.sh"
EOF
          chmod +x AppDir/AppRun

      - name: Build AppImage
        run: |
          ARCH=x86_64 ./appimagetool-x86_64.AppImage \
            AppDir \
            moonlight-wrapper-$ARCH.AppImage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-wrapper.AppImage
          path: moonlight-wrapper-x86_64.AppImage
